waitの仕方を変えた。

diff --git a/.github/workflows/exec.yml b/.github/workflows/exec.yml
--- a/.github/workflows/exec.yml
+++ b/.github/workflows/exec.yml
@@ -20,10 +20,21 @@ jobs:
 
     - name: Wait for MySQL to be ready
       run: |
-        until docker exec db mysqladmin ping -uroot -proot --silent; do
-          echo "Waiting for MySQL to be ready..."
-          sleep 10
+        max_attempts=10
+        attempt=0
+
+        until docker exec db mysqladmin ping -uroot -proot --silent | grep 'mysqld is alivea'; do
+          echo 'Waiting for MySQL to be ready...'
+          sleep 1
+          attempt=$((attempt + 1))
+
+          if [ $attempt -ge $max_attempts ]; then
+            echo 'MySQL failed to become ready after $max_attempts attempts.'
+            exit 1
+          fi
         done
+
+        echo 'MySQL is ready!'
 
     - name: Check Docker containers
       run: docker ps -a
